<a href="https://colab.research.google.com/github/marcus-souza-soares/ml-numpy-week-3/blob/main/numpy_quickstart_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Quickstart for ML

<div style="background-color:#1e293b;padding:15px;border-left:6px solid #38bdf8;color:#e2e8f0">

NumPy is the numerical foundation of Python's machine learning stack. Pandas, scikit-learn, and matplotlib all sit directly on top of NumPy arrays; deep learning frameworks like TensorFlow and PyTorch use their own tensor types but interoperate seamlessly with NumPy.

This notebook covers the parts of NumPy you need to read and write ML code: creating arrays, doing math on them, indexing, the dot product, broadcasting, and why NumPy is dramatically faster than plain Python loops.

You will not need to write NumPy code from scratch in most projects; pandas and scikit-learn do most of the lifting. But knowing the shape of an array, what a dot product is, and how broadcasting works is non-negotiable when you read or debug ML code.

</div>

---
## Step 1: Arrays — Your Numerical Building Block

A NumPy **array** is a grid of numbers with a fixed shape and a single data type. It is the structure ML libraries use to represent vectors of features, matrices of training data, and tensors of higher-dimensional data.

- **1D array** (vector): `[1, 2, 3]` — shape `(3,)`
- **2D array** (matrix): `[[1, 2], [3, 4]]` — shape `(2, 2)`
- **3D array** (tensor): same idea, more dimensions

When you load a CSV into pandas and then hand it to scikit-learn, what scikit-learn actually sees is a 2D NumPy array of shape `(n_samples, n_features)`. Knowing the shape is the first thing you check when something breaks.

In [ ]:
import numpy as np

# Setting a seed makes random operations reproducible:
# the same seed always produces the same sequence of random numbers.
# Standard practice in ML so results match across runs.
np.random.seed(42)

# 1D array from a Python list
vector = np.array([1, 2, 3, 4])
print(f"vector: {vector}")
print(f"shape:  {vector.shape}")
print(f"dtype:  {vector.dtype}")  # data type of each element

# 2D array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\nmatrix:\n{matrix}")
print(f"shape:  {matrix.shape}")  # (rows, columns)

vector: [1 2 3 4]
shape:  (4,)
dtype:  int64

matrix:
[[1 2 3]
 [4 5 6]]
shape:  (2, 3)


### Common ways to create arrays

You will use these constantly:

- `np.zeros(shape)` — array of zeros (good for initialising model weights)
- `np.ones(shape)` — array of ones
- `np.arange(start, stop, step)` — like Python's `range`, but returns an array
- `np.linspace(start, stop, num)` — `num` evenly spaced values from start to stop
- `np.random.rand(d0, d1, ...)` — uniform random values in `[0, 1)`; pass dimensions as separate arguments

In [ ]:
print(f"zeros (2, 3):\n{np.zeros((2, 3))}\n")
print(f"ones (3,):     {np.ones(3)}\n")
print(f"arange:        {np.arange(0, 10, 2)}")        # 0, 2, 4, 6, 8
print(f"linspace:      {np.linspace(0, 1, 5)}")        # 5 values from 0 to 1
print(f"random (2, 2):\n{np.random.rand(2, 2)}")

zeros (2, 3):
[[0. 0. 0.]
 [0. 0. 0.]]

ones (3,):     [1. 1. 1.]

arange:        [0 2 4 6 8]
linspace:      [0.   0.25 0.5  0.75 1.  ]
random (2, 2):
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


**TODO:** Create a 1D array containing the numbers 10, 20, 30, 40, 50. Print its shape. Then create a 3x3 matrix of zeros and print it.

In [ ]:
# YOUR TURN
decimals = np.arange(10, 60, 10)
print(decimals.shape)
print(np.zeros((3,3)))

(5,)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


<details><summary><b>Solution — click to expand</b></summary>

```python
v = np.array([10, 20, 30, 40, 50])
print(v)
print(v.shape)            # (5,)

m = np.zeros((3, 3))
print(m)
```

</details>

---
## Step 2: Element-wise Operations

Math operators on NumPy arrays work **element by element** — no loops needed. The same `+`, `-`, `*`, `/`, `**` you use on numbers works on whole arrays.

This is called **vectorization** and it is the reason NumPy code is both shorter and much faster than the equivalent Python loop.

In [ ]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(f"a + b:  {a + b}")    # element-wise addition
print(f"a * b:  {a * b}")    # element-wise multiplication
print(f"b - a:  {b - a}")
print(f"a ** 2: {a ** 2}")   # element-wise square

# Operations with a scalar apply to every element
print(f"\na * 10:    {a * 10}")
print(f"a + 100:   {a + 100}")

a + b:  [11 22 33]
a * b:  [10 40 90]
b - a:  [ 9 18 27]
a ** 2: [1 4 9]

a * 10:    [10 20 30]
a + 100:   [101 102 103]


> **Note:** Element-wise multiplication `a * b` is **not** the same as the dot product. We will get to the dot product in Step 4.

**TODO:** Given the array of prices below, create a new array where each price has a 15% discount applied (multiply by 0.85).

In [ ]:
prices = np.array([100, 250, 80, 500, 1200])
prices * 0.85

# YOUR TURN: compute discounted prices


array([  85. ,  212.5,   68. ,  425. , 1020. ])

<details><summary><b>Solution — click to expand</b></summary>

```python
discounted = prices * 0.85
print(discounted)   # [ 85.  212.5  68.  425.  1020.]
```

</details>

---
## Step 3: Indexing and Slicing

Indexing pulls out specific elements; slicing pulls out ranges. Both work like Python lists, extended to multiple dimensions.

- `arr[i]` — element at position `i`
- `arr[start:stop]` — range (stop is exclusive)
- For 2D: `matrix[row, col]`, `matrix[:, col]` (a whole column), `matrix[row, :]` (a whole row)

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(f"first element:    {arr[0]}")
print(f"last element:     {arr[-1]}")
print(f"first three:      {arr[:3]}")
print(f"from index 2 on:  {arr[2:]}")
print(f"every other one:  {arr[::2]}")

first element:    10
last element:     50
first three:      [10 20 30]
from index 2 on:  [30 40 50]
every other one:  [10 30 50]


In [ ]:
# 2D indexing — think of it as [rows, columns]
grid = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
])
print(f"grid:\n{grid}\n")

print(f"row 0:            {grid[0, :]}")     # first row
print(f"column 2:         {grid[:, 2]}")     # third column
print(f"element [1, 2]:   {grid[1, 2]}")     # row 1, column 2  -> 7
print(f"top-left 2x2 block:\n{grid[0:2, 0:2]}")

grid:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

row 0:            [1 2 3 4]
column 2:         [ 3  7 11]
element [1, 2]:   7
top-left 2x2 block:
[[1 2]
 [5 6]]


**TODO:** From the `grid` above, extract: (a) the last row, (b) the first column, (c) the element with value `8`.

In [ ]:
# YOUR TURN
print(grid[-1, :])
print(grid[:, 0])
print(grid[1, -1])

[ 9 10 11 12]
[1 5 9]
8


<details><summary><b>Solution — click to expand</b></summary>

```python
print(grid[-1, :])     # [9, 10, 11, 12]  — last row
print(grid[:, 0])      # [1, 5, 9]         — first column
print(grid[1, 3])      # 8                 — row 1, column 3
```

</details>

### Boolean Indexing

You can also index an array with another array of booleans — a **mask**. This is the standard way to filter values by a condition (and to overwrite them in place).

A comparison like `arr > 5` produces a boolean mask the same shape as `arr`. Passing that mask back as the index returns only the elements where the mask is `True`.

Multiple conditions combine with `&` (and), `|` (or), `~` (not) — note these are bitwise operators, not Python's `and`/`or`, which do not work element-wise on arrays.

In [ ]:
data = np.array([1, 5, 8, 3, 9, 2, 7])

# Create a mask: True where data > 5
mask = data > 5
print(f"mask:     {mask}")
print(f"filtered: {data[mask]}")          # only elements where mask is True

# Combine conditions
between = data[(data > 3) & (data < 8)]
print(f"between 3 and 8: {between}")

# Overwrite values in place using a mask
clipped = data.copy()
clipped[clipped < 4] = 0                  # set anything below 4 to 0
print(f"clipped:  {clipped}")

mask:     [False False  True False  True False  True]
filtered: [8 9 7]
between 3 and 8: [5 7]
clipped:  [0 5 8 0 9 0 7]


**TODO:** From the `scores` array below, (a) print only the scores above 80, and (b) create a new array where any score below 60 is replaced with 60.

In [ ]:
scores = np.array([85, 92, 45, 78, 55, 88, 62, 73, 95, 58])

# YOUR TURN
print(scores[scores > 80])
new_scores = scores.copy()
new_scores[scores < 60] = 60
print(new_scores)

[85 92 88 95]
[85 92 60 78 60 88 62 73 95 60]


<details><summary><b>Solution — click to expand</b></summary>

```python
print(scores[scores > 80])              # [85, 92, 88, 95]

floored = scores.copy()
floored[floored < 60] = 60
print(floored)                          # [85, 92, 60, 78, 60, 88, 62, 73, 95, 60]
```

</details>

---
## Step 4: Dot Product and Matrix Multiplication

The **dot product** is the single most important operation in classical ML. Almost every model — linear regression, logistic regression, neural networks — boils down to a dot product between features and learned weights.

**For two 1D arrays** (vectors), the dot product multiplies corresponding elements and sums them:

```
[1, 2, 3] · [4, 5, 6] = 1*4 + 2*5 + 3*6 = 32
```

**For 2D arrays** (matrices), `A @ B` computes the matrix product (this operation is called matrix multiplication) — each cell of the result is a dot product between a row of `A` and a column of `B`. The inner dimensions must match: `(m, n) @ (n, p) → (m, p)`.

NumPy uses `@` (or `np.dot`) for both.

In [ ]:
# 1D dot product — returns a scalar
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(f"a @ b = {a @ b}")                # 32
print(f"check: {1*4 + 2*5 + 3*6}")

a @ b = 32
check: 32


In [ ]:
# 2D matrix multiplication
A = np.array([[1, 2], [3, 4]])           # shape (2, 2)
B = np.array([[5, 6], [7, 8]])           # shape (2, 2)

print(f"A @ B:\n{A @ B}")
# Top-left of the result = row 0 of A dotted with column 0 of B
#                       = 1*5 + 2*7 = 19

A @ B:
[[19 22]
 [43 50]]


In [ ]:
# The ML pattern: predictions = features @ weights
# Imagine 3 houses, each with 2 features [size, bedrooms]
X = np.array([
    [1500, 3],
    [2000, 4],
    [1200, 2],
])                              # shape (3, 2)
weights = np.array([100, 5000]) # shape (2,)

# (3, 2) @ (2,) -> (3,) — one prediction per house
predictions = X @ weights
print(f"predictions: {predictions}")

predictions: [165000 220000 130000]


> **Note:** Shape mismatches are the most common NumPy error. If you ever see `ValueError: shapes (a,b) and (c,d) not aligned`, check the shapes of both operands. For `A @ B`, the inner dimensions must match.

**TODO:** Given the vectors below, compute their dot product. Then compute it manually with `+` and `*` to verify.

In [ ]:
u = np.array([2, 4, 6])
v = np.array([1, 3, 5])

# YOUR TURN: compute u @ v and the manual sum
print(u @ v)
print(2*1 + 4*3 + 6*5)

44
44


<details><summary><b>Solution — click to expand</b></summary>

```python
print(u @ v)                      # 44
print(2*1 + 4*3 + 6*5)            # 44
```

</details>

---
## Step 5: Broadcasting

**Broadcasting** lets NumPy do element-wise operations between arrays of *different but compatible* shapes — by automatically stretching the smaller one along missing dimensions.

The simplest case is array + scalar: the scalar is broadcast to every element. The interesting case is array + smaller array: rows or columns get reused.

Broadcasting is what makes `predictions + bias` and `features - mean` work without writing loops.

In [ ]:
# Array + scalar — the scalar is broadcast to every element
arr = np.array([10, 20, 30])
print(f"arr + 5: {arr + 5}")

arr + 5: [15 25 35]


In [ ]:
# 2D array + 1D array — the 1D array is broadcast across rows
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90],
])                                  # shape (3, 3)
column_offsets = np.array([1, 2, 3])  # shape (3,)

# (3, 3) + (3,) -> column_offsets is broadcast across each row
print(f"data + column_offsets:\n{data + column_offsets}")

data + column_offsets:
[[11 22 33]
 [41 52 63]
 [71 82 93]]


In [ ]:
# Classic ML use: subtract the per-column mean (centering features)
features = np.array([
    [170.0, 70.0],
    [165.0, 65.0],
    [180.0, 80.0],
])                                   # shape (3, 2)

column_means = features.mean(axis=0)  # shape (2,) — mean of each column
print(f"column_means: {column_means}")

centered = features - column_means    # broadcasting subtracts the mean from each row
print(f"centered:\n{centered}")

column_means: [171.66666667  71.66666667]
centered:
[[-1.66666667 -1.66666667]
 [-6.66666667 -6.66666667]
 [ 8.33333333  8.33333333]]


---
## Step 6: Useful Functions

A handful of aggregation functions cover most of what you need. They work on the whole array or — with `axis=` — along rows or columns.

- `np.sum`, `np.mean`, `np.std`, `np.min`, `np.max`
- `axis=0` → aggregate **down columns** (one result per column)
- `axis=1` → aggregate **across rows** (one result per row)
- `arr.reshape(new_shape)` — change shape without changing data
- `arr.T` — transpose (rows become columns)
- `arr.astype(dtype)` — convert to a different data type (e.g. `int` → `float`)

In [ ]:
data = np.array([
    [1, 2, 3],
    [4, 5, 6],
])

print(f"sum (all):       {data.sum()}")           # 21
print(f"mean (all):      {data.mean()}")          # 3.5
print(f"std (all):       {data.std():.3f}")
print(f"max (all):       {data.max()}")

print(f"\ncolumn means (axis=0): {data.mean(axis=0)}")   # [2.5, 3.5, 4.5]
print(f"row means    (axis=1): {data.mean(axis=1)}")     # [2.0, 5.0]

sum (all):       21
mean (all):      3.5
std (all):       1.708
max (all):       6

column means (axis=0): [2.5 3.5 4.5]
row means    (axis=1): [2. 5.]


In [ ]:
# Reshape and transpose
v = np.arange(12)
print(f"original: {v}\n")

m = v.reshape(3, 4)
print(f"reshape(3, 4):\n{m}\n")

print(f"transpose:\n{m.T}")

original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

transpose:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


`arr.astype(dtype)` converts an array to a different data type. The most common ML case: a column loaded as integers that a library needs as floats, or a boolean mask you want to use as a 0/1 feature.

In [ ]:
arr_int = np.array([1, 2, 3, 4])
print(f"original dtype: {arr_int.dtype}")

arr_float = arr_int.astype(float)
print(f"as float64:     {arr_float}   dtype: {arr_float.dtype}")

# Boolean -> int: common when encoding True/False columns for ML models
flags = np.array([True, False, True, True])
print(f"bool -> int:    {flags.astype(int)}")

original dtype: int64
as float64:     [1. 2. 3. 4.]   dtype: float64
bool -> int:    [1 0 1 1]


**TODO:** For the `grades` matrix below (rows = students, columns = subjects), compute:
1. Each student's average grade (one number per row)
2. The average grade per subject (one number per column)

In [ ]:
grades = np.array([
    [80, 75, 90],   # student 1
    [60, 70, 65],   # student 2
    [95, 85, 100],  # student 3
])
print(grades.mean(axis=1))
print(grades.mean(axis=0))

# YOUR TURN


[81.66666667 65.         93.33333333]
[78.33333333 76.66666667 85.        ]


<details><summary><b>Solution — click to expand</b></summary>

```python
print(f"per student: {grades.mean(axis=1)}")    # [81.67, 65.00, 93.33]
print(f"per subject: {grades.mean(axis=0)}")    # [78.33, 76.67, 85.00]
```

Tip: if you forget which axis is which, remember that `axis=0` collapses the first dimension (rows), so you get one result *per column*. `axis=1` collapses columns, leaving one *per row*.

</details>

---
## Step 7: Why NumPy is Fast

NumPy operations run as compiled C under the hood. A pure-Python loop over a million numbers does a million Python-level function calls; the equivalent NumPy operation hands the whole array to one C routine.

Run the cell below to see the speed difference.

In [ ]:
import time

size = 1_000_000
a = np.random.rand(size)
b = np.random.rand(size)
a_list, b_list = a.tolist(), b.tolist()

# Pure Python loop
start = time.time()
result_py = [x + y for x, y in zip(a_list, b_list)]
python_time = time.time() - start

# NumPy vectorized
start = time.time()
result_np = a + b
numpy_time = time.time() - start

print(f"Python loop:  {python_time*1000:7.2f} ms")
print(f"NumPy:        {numpy_time*1000:7.2f} ms")
print(f"Speedup:      {python_time / numpy_time:.0f}x")

Python loop:    77.53 ms
NumPy:           2.43 ms
Speedup:      32x


> **Note:** The speedup compounds. A training loop that runs the same operation millions of times can take seconds with NumPy and minutes (or hours) with a Python loop.

---
## What You Should Be Able to Do Now

- Create 1D and 2D arrays and read their shape and dtype
- Do arithmetic on whole arrays without writing loops
- Index rows, columns, and individual elements of a 2D array
- Filter or modify array values with a boolean mask
- Compute a dot product (`@`) and predict its output shape from input shapes
- Use broadcasting to combine arrays of different shapes
- Aggregate with `sum`, `mean`, `std` along an axis
- Reshape and transpose arrays
- Convert array dtypes with `astype` (e.g. int to float, bool to int)

These are the operations every ML library you will use leans on under the hood.